import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { globalStyles } from './components/styles/globalStyle'
import { globalTheme } from './components/styles/globalTheme'
import { ContainerApp } from "./components/ContainerApp"
import { Header } from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

globalStyles()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <style id='stitches' dangerouslySetInnerHTML={{__html: globalTheme.getCssText()}}/>
      </head>
      <body className={inter.className}>
        <ContainerApp>
          <Header/>
          {children}
        </ContainerApp>
      </body>
    </html>
  )
}
